## 1- Kütüphaneler

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer # BoW yöntemi için gerekli kütüphane
import re

## 2- Veri Seti

In [9]:
# Veri setimizi yükleyelim

df = pd.read_csv("IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

## 3- Metin Ön İşleme - Veri Temizleme

In [10]:
# Metin verileriimizi alalım

comments = df["review"][:100] # 50k veri olduğu için uzun sürecekti. Bu yüzden ilk 100 veri ile çalışıyoruz
labels = df["sentiment"][:100] # 50k veri olduğu için uzun sürecekti. Bu yüzden ilk 100 veri ile çalışıyoruz

In [ ]:
# Metin temizleme fonksiyonu
# Metin temizleme işlemlerini gerçekleştireceğimiz bir fonksiyon yazacacağız

def clean_text(text):
    # küçük harfe çevirme
    text = text.lower()

    # rakamları silelim
    text = re.sub(r"\d+", "", text) # \d - Regex'te bir rakam karakterini temsil eder. Yani 0 ile 9 arasındaki herhangi bir sayı.
                                    # + - - bir veya daha fazla eşleşme anlamına gelir. Yani birden fazla rakam yan yana gelmişse hepsini tek seferde yakalar. (2025 gibi)
    
    # özel karakterleri silelim
    text = re.sub(r"[^\w\s]", "", text) # ^ - Tersleme anlamına gelir. Yani köşeli parantez içindeki karakterler dışındaki karakterleri seçer.
                                       # \w - Kelime karakterini temsil eder. Yani harfler (a-z, A-Z), rakamlar (0-9) ve alt çizgi (_) karakterlerini kapsar.
                                       # \s - Boşluk karakterini temsil eder. Yani boşluk, tab, yeni satır gibi boşluk karakterlerini kapsar.
                                       # Yani bu ifade, kelime karakterleri ve boşluk karakterleri dışındaki tüm karakterleri seçer ve siler.

    # "a, I" gibi tek karakterli kelimeleri silelim
    text = " ".join([word for word in text.split() if len(word) > 2])

    # stop words'leri silelim (sonradan güncellediğimiz kısım)
    import nltk
    from nltk.corpus import stopwords
    nltk.download("stopwords")
    stop_words = set(stopwords.words("english"))
    text = " ".join([word for word in text.split() if word not in stop_words])  # <-- liste yerine string

    return text

In [18]:
#  text = " ".join([word for word in text.split() if len(word) > 2]) fonksiyonu nasıl çalışır?

# deneme_text = "merhaba t dünya"
# print(deneme_text.split())

# [word for word in deneme_text.split() if len(word) > 2] # tek karaterli kelime olan "t"yi almaz

In [19]:
# Metin temizleme işlemini gerçekleştirelim fonksiyonumuzu kullanarak

cleaned_comments = [clean_text(comment) for comment in comments]

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BedirhanOrseloglu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [20]:
# Hem eski hem de temizlenmiş metinlere bakalım

for i in range(5):
    print(f"Eski Metin: {comments[i]}")
    print(f"Temizlenmiş Metin: {cleaned_comments[i]}")
    print()

Eski Metin: One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.
Temizlenmiş Metin: one reviewers mentioned watching episode youll hooked right exactly happened mebr first thing struck brutality unflinching scenes violence set right word trust show faint hearted timid show pulls punches regards drugs sex violence hardcore classic use wordbr called nickname given oswald maximum security state penitentary focuses mainly emerald city experimental section prison cells glass fronts face inwards privacy high agenda city home manyaryans muslims gangstas latinos christians italians irish moreso scuffles death stares dodgy dealings shady agreements never far awaybr would say main appeal show due fact goes shows wouldnt dare forget pretty pictures painted mainstream audiences forget charm forget romanceoz doesnt mess around first episode ever saw struck nasty surreal couldnt say ready watched developed taste got accustomed high levels graphic violence violence injustice crooked guards wholl sold nickel inmates wholl kill order get away well mannered middle class inmates turned prison bitches due lack street skills prison experience watching may become comfortable uncomfortable viewingthats get touch darker side

Eski Metin: A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master's of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional 'dream' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell's murals decorating every surface) are terribly well done.
Temizlenmiş Metin: wonderful little production filming technique unassuming oldtimebbc fashion gives comforting sometimes discomforting sense realism entire piece actors extremely well chosen michael sheen got polari voices pat truly see seamless editing guided references williams diary entries well worth watching terrificly written performed piece masterful production one great masters comedy life realism really comes home little things fantasy guard rather use traditional dream techniques remains solid disappears plays knowledge senses particularly scenes concerning orton halliwell sets particularly flat halliwells murals decorating every surface terribly well done

Eski Metin: I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). While some may be disappointed when they realize this is not Match Point 2: Risk Addiction, I thought it was proof that Woody Allen is still fully in control of the style many of us have grown to love.<br /><br />This was the most I'd laughed at one of Woody's comedies in years (dare I say a decade?). While I've never been impressed with Scarlet Johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.<br /><br />This may not be the crown jewel of his career, but it was wittier than "Devil Wears Prada" and more interesting than "Superman" a great comedy to go see with friends.
Temizlenmiş Metin: thought wonderful way spend time hot summer weekend sitting air conditioned theater watching lighthearted comedy plot simplistic dialogue witty characters likable even well bread suspected serial killer may disappointed realize match point risk addiction thought proof woody allen still fully control style many grown lovebr laughed one woodys comedies years dare say decade ive never impressed scarlet johanson managed tone sexy image jumped right average spirited young womanbr may crown jewel career wittier devil wears prada interesting superman great comedy see friends

Eski Metin: Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them.
Temizlenmiş Metin: basically theres family little boy jake thinks theres zombie closet parents fighting timebr movie slower soap opera suddenly jake decides become rambo kill zombiebr first youre going make film must decide thriller drama drama movie watchable parents divorcing arguing like real life jake closet totally ruins film expected see boogeyman similar movie instead watched drama meaningless thriller spotsbr well playing parents descent dialogs shots jake ignore

Eski Metin: Petter Mattei's "Love in the Time of Money" is a visually stunning film to watch. Mr. Mattei offers us a vivid portrait about human relations. This is a movie that seems to be telling us what money, power and success do to people in the different situations we encounter. <br /><br />This being a variation on the Arthur Schnitzler's play about the same theme, the director transfers the action to the present time New York where all these different characters meet and connect. Each one is connected in one way, or another to the next person, but no one seems to know the previous point of contact. Stylishly, the film has a sophisticated luxurious look. We are taken to see how these people live and the world they live in their own habitat.<br /><br />The only thing one gets out of all these souls in the picture is the different stages of loneliness each one inhabits. A big city is not exactly the best place in which human relations find sincere fulfillment, as one discerns is the case with most of the people we encounter.<br /><br />The acting is good under Mr. Mattei's direction. Steve Buscemi, Rosario Dawson, Carol Kane, Michael Imperioli, Adrian Grenier, and the rest of the talented cast, make these characters come alive.<br /><br />We wish Mr. Mattei good luck and await anxiously for his next work.
Temizlenmiş Metin: petter matteis love time money visually stunning film watch mattei offers vivid portrait human relations movie seems telling money power success people different situations encounter variation arthur schnitzlers play theme director transfers action present time new york different characters meet connect one connected one way another next person one seems know previous point contact stylishly film sophisticated luxurious look taken see people live world live habitatbr thing one gets souls picture different stages loneliness one inhabits big city exactly best place human relations find sincere fulfillment one discerns case people encounterbr acting good matteis direction steve buscemi rosario dawson carol kane michael imperioli adrian grenier rest talented cast make characters come alivebr wish mattei good luck await anxiously next work

# 4- Feature Engeering - Metin Temisili

In [21]:
# CountVectorizer kütüphanemizi kullanarak Bag of Words (BoW) yöntemimizi ele alalım

# İlk olarak nesnemii oluşturalım
vectorizer = CountVectorizer()

# Vektörleştirme işlemini gerçekleştirelim

vectorized_comments = vectorizer.fit_transform(cleaned_comments)

In [22]:
# Kelime kümemizi bulalım
import numpy as np, sys
np.set_printoptions(threshold=sys.maxsize, linewidth=sys.maxsize)  # çıktıda vektörün tamamını görebilmek için ekledik

feature_names = vectorizer.get_feature_names_out()  # Kelime kümesindeki kelimeleri görelim
feature_names

array(['abbot', 'abbreviated', 'abetted', 'abiding', 'ability', 'able', 'aboveaverage', 'abraham', 'abrahams', 'absolute', 'absolutely', 'absorb', 'abstracted', 'absurd', 'abusive', 'academy', 'accent', 'accented', 'accents', 'accentuate', 'accepted', 'accepting', 'accepts', 'accident', 'accidentally', 'accomplish', 'accomplished', 'accomplishes', 'according', 'account', 'accountant', 'accounts', 'accurate', 'accuses', 'accustomed', 'achieve', 'achieved', 'achievement', 'achingly', 'acolyte', 'acquired', 'across', 'acroyd', 'act', 'acting', 'action', 'actions', 'activate', 'actor', 'actors', 'actress', 'actresses', 'acts', 'actual', 'actually', 'ada', 'adabr', 'adams', 'adapted', 'adas', 'add', 'added', 'addict', 'addiction', 'adding', 'addition', 'address', 'adequate', 'adjusterbr', 'admitted', 'adnausem', 'adrian', 'adult', 'advent', 'adventure', 'adventureoh', 'advise', 'affair', 'affairbr', 'affected', 'affection', 'affects', 'afraid', 'africa', 'aftermath', 'afternoons', 'afterwards', 'afterwardsbr', 'againandagain', 'againbr', 'age', 'aged', 'ageing', 'agenda', 'agent', 'aggravate', 'aggression', 'aging', 'agnes', 'ago', 'agobr', 'agree', 'agreements', 'ahab', 'ahead', 'aid', 'aided', 'aids', 'aint', 'air', 'aired', 'airplane', 'airships', 'aka', 'alabama', 'albeit', 'albert', 'album', 'alcoholicbr', 'alcoholism', 'alert', 'alexander', 'alexandra', 'alfred', 'ali', 'alice', 'alien', 'alienation', 'alive', 'alivebr', 'allen', 'alley', 'allinall', 'allison', 'allowed', 'alltime', 'alltogether', 'allusionshomagesripoffs', 'ally', 'almost', 'alone', 'along', 'alot', 'already', 'also', 'although', 'altogether', 'alvarado', 'always', 'amateurish', 'amazing', 'amber', 'ambiguity', 'ambitious', 'america', 'american', 'americans', 'americas', 'amnesia', 'among', 'amongst', 'amount', 'amusing', 'anand', 'anands', 'anatomy', 'anchor', 'andbr', 'andor', 'andrew', 'angeles', 'anger', 'angering', 'angie', 'angle', 'angled', 'angles', 'angry', 'animal', 'animals', 'animated', 'animation', 'anime', 'anna', 'annoying', 'another', 'ant', 'antagonistic', 'anthology', 'anthony', 'antics', 'antilabor', 'antiquities', 'antireligious', 'antisemitism', 'antiwar', 'anxiously', 'anybody', 'anymore', 'anymorebr', 'anyone', 'anything', 'anythingbr', 'anyway', 'anywaybr', 'anywhere', 'anywherebr', 'apart', 'apartment', 'apologize', 'apparent', 'apparently', 'appeal', 'appealing', 'appear', 'appearance', 'appearbr', 'appeared', 'appearing', 'appears', 'applause', 'appliedbr', 'appreciate', 'appreciation', 'approach', 'approached', 'arab', 'archaeologists', 'ardh', 'area', 'areas', 'arent', 'arff', 'arguing', 'arielle', 'aristocratic', 'armies', 'arms', 'army', 'around', 'arquette', 'arrange', 'arranged', 'array', 'arrehman', 'arrest', 'arrived', 'arriving', 'art', 'arthur', 'artillery', 'artist', 'artistic', 'artists', 'arts', 'ashes', 'asians', 'aside', 'ask', 'asking', 'aspect', 'aspects', 'assigned', 'assistants', 'associated', 'assume', 'assuming', 'assured', 'astonishing', 'astonishingly', 'astronauts', 'asylumis', 'atkins', 'atmosphere', 'atrocities', 'atrocity', 'attached', 'attachment', 'attack', 'attacked', 'attacking', 'attempt', 'attempting', 'attempts', 'attending', 'attest', 'attitudeand', 'attractions', 'attractive', 'aubrey', 'audience', 'audiencebr', 'audiences', 'auer', 'australia', 'australian', 'authenticity', 'authorities', 'available', 'avenge', 'average', 'averaged', 'aviation', 'avoid', 'await', 'awake', 'awaken', 'awakening', 'awakeningly', 'awards', 'aware', 'away', 'awaybr', 'awesome', 'awful', 'awfulbr', 'awhupping', 'awkwardly', 'axed', 'babes', 'baby', 'bacio', 'back', 'background', 'bad', 'badass', 'badbr', 'baddies', 'badness', 'badventure', 'baffles', 'balance', 'ball', 'ban', 'banal', 'band', 'bank', 'banknotes', 'banned', 'banter', 'bar', 'barbara', 'barely', 'bargain', 'bargaining', 'barker', 'barnes', 'barry', 'bars', 'bart', 'baseball', 'based', 'basejumping', 'basement', 'basically', 'bat', 'battle', 'battlefield', 'battling', 'bay', 'beach', 'beaches', 'bearablebr', 'beat', 'beats', 'beautiful', 'beautifully', 'beautifullytrained', 'beauty', 'bebr', 'became', 'become', 'becomes', 'bed', 'bedroom', 'beds', 'beenbr', 'beforebr', 'began', 'begging', 'begin', 'beginbr', 'beginning', 'begins', 'beginsbr', 'begun', 'behavior', 'behind', 'behindbr', 'beings', 'bela', 'belas', 'believability', 'believable', 'believe', 'believing', 'bellastyle', 'belle', 'belligerent', 'belongs', 'belted', 'benefit', 'benefits', 'berkshire', 'bernstein', 'besides', 'best', 'bet', 'bette', 'better', 'beyond', 'biblical', 'big', 'bigbreasted', 'bigger', 'biggest', 'bigots', 'bill', 'billboard', 'billed', 'bimbo', 'binnie', 'birch', 'bird', 'bisexual', 'bismillahhirrahmannirrahim', 'bit', 'bitbr', 'bitch', 'bitches', 'bits', 'bitter', 'bivouacked', 'biz', 'bizarre', 'black', 'blackbr', 'blacks', 'blade', 'bland', 'blast', 'blasting', 'blatant', 'blatantly', 'blaze', 'bleeding', 'blitz', 'block', 'blockbuster', 'blood', 'bloodbath', 'bloodshedbr', 'bloody', 'blowing', 'blows', 'bluff', 'bluffed', 'blunt', 'blurb', 'blurred', 'bmovie', 'bmovies', 'bmw', 'board', 'boardbr', 'boards', 'boat', 'bobs', 'bodies', 'bog', 'bohemian', 'boldness', 'boll', 'bolls', 'bombed', 'bombs', 'bombshell', 'bonbons', 'bond', 'bonfire', 'bonus', 'boogeyman', 'book', 'books', 'boom', 'booming', 'booth', 'border', 'borders', 'bore', 'bored', 'boring', 'born', 'boss', 'bossy', 'bother', 'bottom', 'bought', 'bound', 'boundaries', 'bout', 'bowdler', 'bowdlerization', 'bows', 'bowser', 'box', 'boy', 'boys', 'brad', 'brady', 'brain', 'brains', 'brand', 'brandishing', 'bratwurst', 'brave', 'bravo', 'bread', 'breakdown', 'breaking', 'breaks', 'breasts', 'breed', 'brendan', 'brenner', 'brevity', 'brews', 'brick', 'brides', 'brief', 'bright', 'brilliance', 'brilliant', 'brilliantly', 'brilliantlybr', 'bring', 'brings', 'brit', 'british', 'broadbent', 'brodie', 'brodys', 'broke', 'brooks', 'brother', 'brothers', 'brought', 'brown', 'brush', 'brutal', 'brutality', 'btw', 'bucket', 'buddy', 'budget', 'buffoon', 'bug', 'build', 'building', 'builds', 'buildup', 'bull', 'bulletpellet', 'bullets', 'bullshits', 'bully', 'bullying', 'bumped', 'bunch', 'bureau', 'burning', 'buscemi', 'busey', 'bush', 'business', 'businessmen', 'busted', 'busty', 'busy', 'busybody', 'butcher', 'butler', 'button', 'buyerbr', 'caddy', 'caddyshack', 'cage', 'cages', 'cajole', 'caliber', 'california', 'call', 'called', 'calling', 'camcorder', 'came', 'cameo', 'camera', 'cameras', 'camp', 'campbell', 'campfire', 'canaanites', 'canada', 'canadian', 'candle', 'candy', 'cannot', 'cant', 'canton', 'capable', 'capped', 'captain', 'captor', 'captors', 'capture', 'captured', 'captures', 'car', 'caravan', 'cardboard', 'care', 'career', 'careerbr', 'cares', 'caricatured', 'caricatures', 'caring', 'carol', 'carolina', 'carpenter', 'carpenters', 'carpet', 'carrey', 'carries', 'carry', 'carver', 'case', 'casebr', 'cases', 'casesbr', 'cash', 'cashed', 'cast', 'casting', 'castle', 'castros', 'casualty', 'caught', 'cause', 'causes', 'cecil', 'cedric', 'celebrating', 'celebration', 'cell', 'cellphone', 'cells', 'censors', 'centers', 'central', 'centuries', 'century', 'cerda', 'cerdas', 'cerebral', 'certain', 'certainly', 'certainty', 'chain', 'challenge', 'challenging', 'chamber', 'chambermaids', 'chance', 'chances', 'change', 'changed', 'changes', 'character', 'characterbr', 'characterdriven', 'characteristic', 'characters', 'charles', 'charleton', 'charlton', 'charm', 'chatting', 'cheap', 'cheaper', 'check', 'cheerleaders', 'cheese', 'cheesy', 'chemistry', 'chick', 'chided', 'child', 'childhood', 'children', 'childrens', 'chillers', 'chilling', 'chillingly', 'chills', 'china', 'chip', 'chippindalemaybe', 'chooses', 'choreographed', 'chose', 'chosen', 'chris', 'christians', 'christopher', 'chronology', 'chum', 'church', 'cigarfellatio', 'cinecittà', 'cinema', 'cinematography', 'circle', 'circles', 'circus', 'cities', 'citizen', 'citizens', 'city', 'citys', 'civil', 'civilians', 'clad', 'clairvoyancebr', 'clarity', 'class', 'classic', 'classical', 'classics', 'classified', 'clear', 'clearly', 'clever', 'cliche', 'cliches', 'clichéd', 'clichés', 'cliffhanger', 'climax', 'climbed', 'climbing', 'clint', 'clips', 'clock', 'clone', 'clooney', 'close', 'closely', 'closes', 'closest', 'closet', 'cloying', 'club', 'clue', 'clues', 'clumsy', 'clunky', 'cmon', 'coauthored', 'coaxing', 'coburn', 'coburns', 'cocktail', 'coffins', 'coincidence', 'cold', 'collateral', 'colleagues', 'colleen', 'collegecrocodile', 'collins', 'colorful', 'combat', 'come', 'comeback', 'comedic', 'comedies', 'comedy', 'comes', 'comfortable', 'comforting', 'comical', 'comin', 'coming', 'comment', 'commentary', 'comments', 'commercial', 'commission', 'committing', 'common', 'communicated', 'communism', 'company', 'companybr', 'compare', 'compared', 'comparison', 'compelling', 'compete', 'complained', 'complaint', 'complaints', 'complete', 'completely', 'complex', 'composition', 'compromise', 'computer', 'con', 'concedes', 'concept', 'concern', 'concerned', 'concerning', 'conclusion', 'conclusive', 'condition', 'conditioned', 'conducting', 'confederate', 'confederates', 'confidence', 'confined', 'conflict', 'confrontation', 'confused', 'confusing', 'connect', 'connected', 'connection', 'connections', 'conseguenze', 'consequences', 'consider', 'considered', 'consist', 'consisting', 'consists', 'conspiracy', 'constable', 'constant', 'constantly', 'constructed', 'contact', 'contain', 'contained', 'contains', 'continued', 'continuing', 'continuity', 'continuous', 'contrast', 'contrivedbr', 'control', 'controls', 'conveniently', 'convent', 'conversation', 'conveyed', 'convicts', 'convincing', 'cool', 'coolest', 'cooper', 'coot', 'cop', 'cope', 'cops', 'core', 'corner', 'corporatization', 'corpse', 'correct', 'corruption', 'cosmos', 'cost', 'costumes', 'could', 'couldnt', 'count', 'counterpart', 'counting', 'countries', 'country', 'countrybr', 'countrymen', 'couple', 'couplebr', 'courage', 'course', 'courtenay', 'covered', 'covering', 'coz', 'cracking', 'craig', 'cramming', 'crap', 'crappy', 'craving', 'crazy', 'create', 'created', 'creates', 'creating', 'creation', 'creations', 'creator', 'creators', 'creature', 'creaturekillerwhatever', 'creatures', 'credibility', 'credited', 'credits', 'creepiness', 'creepy', 'creepywoman', 'cried', 'crime', 'crimes', 'criminals', 'cringeworthy', 'cripple', 'crisis', 'crisp', 'crissakes', 'cristy', 'cristys', 'critic', 'criticize', 'critics', 'critique', 'croc', 'crock', 'crocky', 'crocodile', 'crocodiles', 'crododile', 'cromedalbino', 'cronenbergs', 'crooked', 'cropper', 'cross', 'crossfire', 'crown', 'croûtons', 'crude', 'crumby', 'crumpet', 'crusade', 'cry', 'cub', 'cuba', 'cuckolding', 'culminates', 'cult', 'cultured', 'cummings', 'curator', 'cure', 'curiosity', 'curiositywanting', 'curious', 'curiously', 'current', 'currently', 'curry', 'curt', 'custody', 'cut', 'cute', 'cutiebr', 'cuts', 'cyclebr', 'cynthia', 'dad', 'daft', 'dallas', 'damatos', 'damn', 'damned', 'dan', 'dance', 'dancers', 'dancing', 'dangerfield', 'dangerous', 'dangling', 'daniel', 'danny', 'daphne', 'dara', 'dare', 'daredevil', 'daring', 'dark', 'darkbr', 'darker', 'datebr', 'dated', 'daughter', 'daughters', 'daughtersbr', 'david', 'davies', 'davis', 'dawson', 'day', 'daylewis', 'days', 'daysbr', 'dead', 'deadbeat', 'deadlier', 'deadly', 'deaf', 'deafmute', 'dealing', 'dealings', 'dealt', 'deanna', 'death', 'deathbr', 'deaths', 'debentures', 'decade', 'deceives', 'decent', 'deceptions', 'deceptive', 'decide', 'decided', 'decides', 'decisions', 'declaration', 'decline', 'decorating', 'decors', 'dedication', 'deep', 'deeper', 'deeply', 'definitely', 'degenerates', 'degree', 'deliberate', 'delight', 'delightful', 'delivered', 'delivers', 'dellamore', 'demented', 'demilles', 'demure', 'denied', 'denigrated', 'denouement', 'dense', 'dentistry', 'deparidieu', 'dependent', 'depict', 'depicted', 'depiction', 'depresses', 'depression', 'depth', 'derivative', 'descent', 'describe', 'described', 'describes', 'desert', 'deserter', 'deserve', 'design', 'desired', 'desires', 'despair', 'desperate', 'despite', 'destroy', 'destroys', 'detail', 'details', 'detailsbr', 'detective', 'determined', 'detonate', 'detriment', 'develop', 'developed', 'development', 'devices', 'devil', 'dialog', 'dialogs', 'dialogue', 'diary', 'didnt', 'die', 'died', 'dies', 'difference', 'different', 'difficult', 'dig', 'digital', 'digitally', 'dignitary', 'dignity', 'dimensional', 'diminishes', 'diminutive', 'dinosaurs', 'dire', 'directed', 'directing', 'direction', 'directionbr', 'director', 'directorial', 'directors', 'disappears', 'disappointed', 'disappointing', 'disappointment', 'disapproves', 'disaster', 'disbelief', 'discerns', 'disclaimer', 'discomforting', 'disconcerting', 'discover', 'discovered', 'discoveries', 'discovers', 'discovery', 'discreet', 'discusses', 'discussing', 'disease', 'disgraceful', 'disgruntled', 'disgusted', 'disgusting', 'dish', 'dishwaterdull', 'disjoined', 'dismal', 'dismiss', 'disneyland', 'disobedience', 'displays', 'distance', 'distant', 'distinctive', 'distraction', 'disturbing', 'ditzy', 'diversioni', 'divorce', 'divorced', 'divorcing', 'dizzying', 'dmytryk', 'dmytryks', 'doc', 'doctor', 'doctrinaire', 'documentary', 'dodgy', 'doesnt', 'doll', 'dollars', 'dominoes', 'done', 'dont', 'doom', 'door', 'dorothy', 'double', 'doubt', 'doug', 'douglas', 'douses', 'downhill', 'downhillbr', 'downward', 'dozen', 'drag', 'dragging', 'drags', 'drama', 'dramaticness', 'drastic', 'drawn', 'draws', 'dreadful', 'dream', 'drenched', 'dressed', 'dressedup', 'dresser', 'dresses', 'drew', 'drives', 'dropped', 'drops', 'drove', 'drug', 'drugs', 'drum', 'drummer', 'drunk', 'dry', 'dub', 'dubbed', 'duckling', 'dudes', 'due', 'dues', 'duffy', 'dull', 'dullbr', 'dumariers', 'dumb', 'dummy', 'dung', 'dunnit', 'duplicating', 'durbin', 'dutcher', 'dutchers', 'dvd', 'dwarf', 'dyemill', 'eachother', 'earlier', 'earlierbr', 'early', 'earthreally', 'ease', 'easier', 'easily', 'eastwood', 'easy', 'eat', 'eating', 'ebola', 'eddie', 'edge', 'edited', 'editing', 'editor', 'edward', 'eerie', 'effect', 'effective', 'effects', 'effectsbr', 'effort', 'efforts', 'eight', 'eileen', 'einstein', 'either', 'elder', 'elderly', 'elders', 'election', 'elegant', 'elegantly', 'elektra', 'element', 'elements', 'eleven', 'elicit', 'elijah', 'else', 'elsebr', 'elsewhere', 'elucidate', 'embarks', 'emboldened', 'emerald', 'emerge', 'emmy', 'emotional', 'emotions', 'emphasis', 'emphasize', 'empire', 'employee', 'employees', 'employer', 'empty', 'encompasses', 'encounter', 'encounterbr', 'encounters', 'encourage', 'encouraged', 'encouraging', 'end', 'endbr', 'ended', 'ending', 'ends', 'endurance', 'enemies', 'energetic', 'engaged', 'engaging', 'engine', 'england', 'english', 'enhanced', 'enjoy', 'enjoyable', 'enjoyed', 'enjoying', 'enough', 'ensues', 'enter', 'entering', 'enters', 'entertain', 'entertained', 'entertaining', 'entertainment', 'entire', 'entirely', 'entiretybr', 'entity', 'entrailing', 'entrails', 'entries', 'environment', 'environmentalismor', 'environmentbr', 'environments', 'epic', 'epidemic', 'episode', 'equally', 'equivalent', 'era', 'erabr', 'erase', 'erect', 'eriksen', 'erotic', 'errol', 'especially', 'espionage', 'essential', 'estate', 'etc', 'eurasian', 'europe', 'european', 'eve', 'even', 'evening', 'eveningbr', 'event', 'events', 'eventually', 'ever', 'every', 'everybody', 'everyone', 'everything', 'eves', 'evidence', 'evident', 'evil', 'evilness', 'evoke', 'evolve', 'exact', 'exactly', 'example', 'examples', 'examplesbr', 'exceeded', 'excellent', 'except', 'exception', 'excessive', 'excited', 'excitement', 'excuses', 'exdrug', 'executing', 'execution', 'exist', 'existence', 'exists', 'exlover', 'exotic', 'expands', 'expect', 'expectation', 'expectations', 'expected', 'expecting', 'expensive', 'experience', 'experienced', 'experiences', 'experiment', 'experimental', 'expert', 'explain', 'explaining', 'explains', 'explanation', 'explanations', 'explicit', 'explicitly', 'exploitation', 'exploitationmonster', 'exploitative', 'explore', 'exposed', 'exposure', 'expressed', 'expressions', 'expressive', 'extended', 'extracts', 'extras', 'extreme', 'extremely', 'eye', 'eyegouging', 'eyepopping', 'eyes', 'face', 'faces', 'facial', 'fact', 'factor', 'factory', 'facts', 'factual', 'fade', 'fail', 'failed', 'failings', 'fails', 'faint', 'fair', 'fairbrass', 'fairly', 'faith', 'faithful', 'fake', 'fall', 'fallen', 'falls', 'falters', 'familiar', 'family', 'familybr', 'famous', 'fan', 'fans', 'fantastic', 'fantasy', 'far', 'farce', 'fare', 'farfetched', 'farm', 'fascinating', 'fashion', 'fast', 'fate', 'father', 'fathers', 'fault', 'faults', 'faust', 'faux', 'favored', 'favorite', 'favourite', 'fbi', 'fear', 'feast', 'feature', 'feel', 'feelgood', 'feeling', 'feels', 'fell', 'fellow', 'felt', 'female', 'females', 'fences', 'ferocious', 'fest', 'fetishists', 'fiction', 'fields', 'fiery', 'fifteen', 'fiftys', 'fight', 'fighting', 'fights', 'figure', 'figured', 'filled', 'film', 'filmbr', 'filmed', 'filmgoing', 'filming', 'filmit', 'filmmaker', 'films', 'filmwhether', 'final', 'finale', 'finales', 'finally', 'financing', 'find', 'finding', 'finds', 'fine', 'finest', 'fing', 'fingersmith', 'finish', 'finishedbr', 'finney', 'finsished', 'fire', 'fired', 'firing', 'first', 'fisherman', 'fishies', 'fit', 'fitness', 'fits', 'five', 'fiver', 'flair', 'flat', 'flavor', 'flaws', 'fleeing', 'fletcher', 'flick', 'flicks', 'flimsy', 'floating', 'flock', 'flood', 'floor', 'flow', 'fluid', 'flush', 'flying', 'flynn', 'fmovie', 'focus', 'focuses', 'fodder', 'fog', 'folks', 'follow', 'followed', 'followers', 'following', 'follows', 'fond', 'fooled', 'foot', 'football', 'force', 'forced', 'foreboding', 'foremost', 'forewarnedbr', 'forget', 'forgettable', 'forgive', 'forgiveness', 'forgotten', 'form', 'formed', 'former', 'formula', 'formulaic', 'formulas', 'formulated', 'forte', 'forthcoming', 'forward', 'foster', 'fought', 'foul', 'found', 'four', 'foxhole', 'framed', 'france', 'franchise', 'franchot', 'francis', 'frank', 'freaks', 'fred', 'freds', 'free', 'french', 'frequent', 'fresh', 'friction', 'friend', 'friends', 'friendship', 'frodo', 'front', 'fronts', 'frustrating', 'frustrations', 'frye', 'fugitive', 'fulci', 'fulcis', 'fulfillment', 'full', 'fuller', 'fulltime', 'fully', 'fullyfledged', 'fumes', 'fun', 'funbr', 'funding', 'funneled', 'funniest', 'funny', 'funnyalmostbr', 'furthermore', 'future', 'gained', 'gaira', 'galaxies', 'galaxy', 'galloping', 'game', 'gamesbr', 'gamin', 'gang', 'gangs', 'gangstas', 'gangster', 'gangsters', 'garner', 'garners', 'gary', 'gate', 'gathers', 'gave', 'gawked', 'gaybashing', 'gear', 'geared', 'gehrigs', 'gellar', 'gem', 'gembr', 'general', 'generating', 'genesis', 'geneticallymutatedsoldiers', 'genius', 'geniuses', 'genre', 'genres', 'gentle', 'genuine', 'geologists', 'george', 'german', 'get', 'gets', 'getting', 'ghost', 'ghosts', 'ghoulies', 'giallo', 'giallomurdermystery', 'gibb', 'gilbert', 'gilberts', 'girl', 'girlfriend', 'girls', 'girolamo', 'girolamos', 'give', 'given', 'gives', 'giving', 'glad', 'gladys', 'glamorous', 'glance', 'glass', 'glassbr', 'glazing', 'gleeson', 'glib', 'globe', 'gloomy', 'gloria', 'gloriously', 'glory', 'glued', 'glut', 'gms', 'gobsmackedbr', 'god', 'godbr', 'gods', 'godzilla', 'goes', 'going', 'golddigger', 'golden', 'goldie', 'goldies', 'golf', 'gone', 'gonna', 'good', 'goodbr', 'goodbye', 'gooding', 'goodness', 'gordon', 'gore', 'gory', 'got', 'gothic', 'govind', 'grabbing', 'grace', 'grade', 'grading', 'gradually', 'grahame', 'grain', 'grainy', 'grammar', 'granddaughter', 'grandfather', 'grandiose', 'grandma', 'grandmothers', 'grandson', 'graphic', 'graphics', 'grave', 'graves', 'gravity', 'great', 'greatest', 'greatly', 'greed', 'greetings', 'grenier', 'grew', 'grey', 'grinning', 'gripes', 'gripping', 'grizzly', 'gross', 'grote

In [23]:
len(feature_names)  # kelime kümemizde 4889 adet benzersiz kelimemiz varmış.

4796

In [24]:
# Vektör temsilimizi oluşturalım
import numpy as np, sys
np.set_printoptions(threshold=sys.maxsize, linewidth=sys.maxsize)  # çıktıda vektörün tamamını görebilmek için ekledik

print(f"Vektör temsili: {vectorized_comments.toarray()[:2]}") # ilk 2 cümlemize baktık

# Bu çıktıda 2 satır (yorum) 4889 sütun (kelime kümemiz) var
# Örneğin ilk cümlede 6 numaralı kelimemiz (about) varmış (kelimeyi bulmak için kelime kümemizi inceleyelebiliriz.)

Vektör temsili: [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 3 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]

In [25]:
# Daha güzel inceleyebilmek için DataFrame'e çevirelim

df_bow = pd.DataFrame(vectorized_comments.toarray(), columns=feature_names)
df_bow.head()

# ilk cümlede "about" kelimesinin olduğunu yine görebiliyoruz (0. satır ve about sütunu kesişimi)

,abbot,abbreviated,abetted,abiding,ability,able,aboveaverage,abraham,abrahams,absolute,...,zany,zellweger,zerog,zeus,zombie,zombiebr,zone,zoo,zooms,zwick
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# # Yukarıdaki df'in tüm sütunları görmek istersek

# df_bow = pd.DataFrame(vectorized_comments.toarray(), columns=feature_names)

# # Tüm sütunların kesilmeden gösterilmesi için pandas ayarları
# import pandas as pd
# from IPython.display import display
# pd.set_option('display.max_columns', None)
# pd.set_option('display.width', None)
# pd.set_option('display.max_colwidth', None)

# # İlk 5 satırı tüm sütunlarla gör
# display(df_bow.head())

In [27]:
# Her bir kelimenin frekansını bulalım
word_counts = vectorized_comments.sum(axis=0).A1  # A1 ile 2D array'ı 1D array'a çeviriyoruz
word_counts

array([  1,   1,   2,   2,   1,   2,   1,   1,   1,   1,   7,   1,   1,   2,   1,   1,   2,   1,   1,   1,   3,   1,   1,   2,   1,   1,   1,   1,   2,   1,   1,   1,   3,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   7,  27,   6,   1,   1,   9,  19,   6,   2,   1,   4,  16,   4,   1,   1,   1,   2,   1,   2,   1,   1,   3,   2,   1,   1,   1,   1,   1,   2,   2,   1,   5,   1,   1,   3,   1,   3,   1,   1,   2,   1,   4,   1,   1,   1,   1,   1,   2,   1,   1,   2,   2,   1,   1,   2,   1,   2,   1,   1,   1,   1,   1,   1,   1,   1,   1,   4,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   3,   1,   1,   1,   1,   1,   3,   1,   1,   1,   1,   1,   2,   1,   1,   1,   1,   9,   2,   7,   1,   3,  30,  11,   3,   2,   5,   2,   4,   1,   1,   1,   3,   4,   1,   1,   1,   5,   2,   3,   2,   4,   2,   1,   1,   1,   2,   1,   1,   1,   1,   2,   1,   1,   1,   1,   1,   1,   1,   2,   2,   1,   4,  19,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,   2,   2,   1,  13,   6,   1,   2,   1,   2,   1,   1,   2,   1,   1,   5,   2,   1,   2,   2,   1,   1,   2,   3,   1,   1,   2,   1,   3,   1,   1,   1,   2,   1,   1,   2,   3,   1,   1,   1,   1,   2,   4,  17,   1,   1,   1,   1,   1,   1,   1,   1,   3,   1,   1,   1,   1,   1,   4,   1,   1,   2,   1,   1,   1,   2,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,   1,   1,   2,   1,   1,   5,   1,   2,   1,   1,   1,   2,   1,   1,  14,   1,   2,   3,   1,   1,   1,   2,   2,   1,   6,   1,   1,   2,   1,   1,   1,   1,   1,   1,   3,  10,   1,   2,   9,   1,   1,   1,   1,   1,   1,   1,  19,   2,  36,   2,   1,   1,   1,   1,   1,   1,   1,   1,   2,   4,   2,   1,   1,   1,   1,   2,   3,   1,   1,   1,   4,   2,   2,   1,   1,   8,   1,   1,   4,   1,   3,   1,   1,   2,   1,   1,   1,   1,   1,  10,   2,   1,   1,   1,   1,   9,  12,   1,   1,   1,   1,   2,   4,   1,   2,   1,  10,   4,   1,   1,   1,   5,   1,   1,   4,   1,   1,   5,  10,   1,   1,   1,   2,   1,   1,   1,   1,   1,   1,   1,  24,   1,   2,  20,   5,   1,  14,   1,   3,   1,   1,   3,   1,   1,   1,   1,   1,   1,   1,   1,  10,   1,   1,   1,   2,   1,   1,   1,   3,   9,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   4,   6,   1,   1,   1,   1,   2,   3,   1,   1,   1,   1,   8,   3,   1,   3,   1,   1,   1,   1,   1,   1,   1,   1,   5,   2,   1,   1,   1,   1,   1,   1,   1,   1,   7,   1,   1,   1,   1,   1,   2,   2,   5,   6,   1,   2,   1,   1,   2,   3,   1,   1,   1,   1,   1,   1,   4,   1,   5,   1,   1,   3,   2,   2,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,   1,   1,   1,   1,   1,   2,   1,   2,   3,   3,   1,   1,  10,   5,   1,   1,   1,   1,   1,   1,   2,   2,   2,   6,   3,   1,   2,   1,   1,   1,   1,   2,   1,   1,   2,   2,   1,   2,   1,   1,   2,   1,   1,   1,   1,   2,   1,   2,   1,   1,   3,   6,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,   1,   1,   1,   4,   7,   1,   1,   8,   2,   3,   1,   2,   2,   1,   2,   1,   1,   1,   1,   5,  21,   1,   2,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,   4,   1,   1,   2,   1,   1,   1,   1,   2,   3,   1,   1,   3,   1,   1,   5,   5,   1,   1,   1,   1,   1,  15,   1,   5,   1,   1,   2,   5,   2,   1,   1,   1,   1,   5,   1,   1,   1,   2,   1,   1,   4,   2,   1,   1,   1,   6,   1,   1,   1,   1,   2,   1,   4,   1,   5,   3,   2,  26,   1,   1,   1,  24,   3,   1,   1,   2,   1,   4,   1,   1,   1,   1,   3,   2,   1,   1,   6,   3,   5,   1,   1,   1,   1,   1,   2,   1,   1,   1,   1,   2,   1,   1,   2,   1,   1,   1,   1,   1,   1,   9,   2,   1,   1,   2,   1,   2,   1,   6,   1,   2,   1,   1,   1,   1,   2,   6,   1,   1,   1,   2,   3,   1,   1,   1,   1,   2,   2,   2,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,   1,   2,   1,   1,   1,   1,   1,   2,   1,   1,   1,   7,   1,   1,   1,   1,   6,   1,   2,   1,   1,   2,   1,   1,   5,   1,   2,   1,   9,  12,   1,   2,   1,   1,   4,   1,   1,   2,   1,   1,   1,   1,   1,   1,   2,   1,   1,   3,   2,   3,   1,   1,   1,   1,   3,   8,   2,   1,   1,   2,   1,   1,   1,   2,   1,   1,   2,   1,   1,   1,   2,   1,   1,   1,   1,   1,   1,   2,   3,   1,   1,   1,   1,   4,   3,   1,   2,   1,   1,   1,   1,   1,   3,   4,   1,   1,   1,   1,   2,   2,   1,   1,   1,   2,   1,   4,   1,   1,   1,   2,   1,   1,   3,   1,   1,   1,   1,   2,   2,   4,   1,   1,   1,   2,   2,   2,   1,   1,   2,  34,   4,   3,   1,   2,   1,   3,   1,   1,   5,   1,   1,  10,   5,   1,   1,   1,   1,   1,   1,   2,   4,   1,   2,   3,   3,   1,   3,   1,   1,   1,   2,   2,   1,   3,   1,   1,   1,   1,   1,   1,   1,   3,   1,   1,   2,   1,   1,   1,   1,   4,   1,   1,   1,   1,   2,   1,   2,   4,   4,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,   1,   1,   1,   1,   6,   1,   2,   1,   1,   2,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   4,   1,   1,   1,   1,   1,   3,   1,   1,   1,   2,   1,   2,   2,   1,   3,   1,   2,   1,   2,   1,   1,   2,   2,   1,   1,   7,   1,   3,   1,   4,   4,   1,   1,   3,   1,   3,   1,   5,   2,   3,   1,   1,   1,   1,   1,   2,   1,   2,   1,   3,   3,   7,   1,   2,   1,   1,   1,   3,   1,   1,   2,   2,   5,   1,   2,   2,   1,   2,   1,   4,   1,   3,   4,   1,   1,   1,   1,   3,   1,   3,   4,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   3,   1,   1,   1,   1,   3,   2,   1,   1,   5,   1,   1,   2,   1,   1,   3,   2,   1,   1,   1,   2,   3,   1,   1,   3,   1,   8,   1,  15,   3,   2,   1,   2,  12,   4,   1,   1,   1,   1,   1,   2,   1,   1,   1,   1,   2,   2,   7,   1,  14,   1,   3,   1,   6,   3,   2,   1,   3,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,   1,   2,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,   2,   1,   3,   1,  11,   1,   1,   1,   8,  32,   1,   4,   1,   3,   2,   3,   1,   1,   2,   1,   1,   5,   1,   1,   1,   6,   2,   1,   2,   1,   1,   4,   1,   2,   1,   6,   1,   1,   1,   2,   2,   1,   1,   2,   1,   2,   3,   1,   1,   3,   2,   1,   5,   1,   1,   2,   1,   1,   2,   1,   1,   1,   1,   4,   5,   1,   8,   1,   1,   1,   8,   1,   4,   1,   1,   3,   1,   1,   1,   1,   3,   1,   1,   1,   2,   2,   1,   2,   1,   2,   1,   8,   1,   3,   1,   1,   2,   1,   4,   1,   1,   1,   1,   1,   1,   1,   1,   5,   1,   1,   1,   5,   1,   1,   1,   1,   1,   1,   1,   1,   3,   1,   1,   1,   1,   2,   1,   3,   1,   1,   1,   1,   1,   1,   2,   1,  25,   2,   1,   6,   1,   1,   1,   1,   1,   1,   1,   2,   3,   1,   7,   2,   3,   1,   9,   1,   2,   1,   2,   1,   1,   6,   9,   7,   4,   1,   2,   1,   3,   1,   1,   1,   1,   1,   2,   1,   3,   1,   2,   1,   2,   1,   1,   3,   1,   1,   9,   2,   1,   1,   2,   1,   1,   1,   2,  58,   2,   1,   1,   1,   5,  17,   9,   2,   4,   9,   1,   1,   1,   5,   1,   1,   1,   1,   5,   9,   1,   1,   1,   4,   4,   3,   1,   1,   2,   1,   1,   1,   2,   1,   2,   1,   1,   1,   1,   3,   1,   3,   2,   1,   1,   4,   1,   2,   1,   1,   2,   2,   1,   2,   2,   1,   3,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   5,   4,   1,   1,   9,   7,   1,   2,  13,   1,   2,   2,   1,   1,   1,   3,   1,   4,   1,   2,   1,   1,   2,   1,   3,   2,   1,   6,   1,   4,   7,   1,   3,   7,   4,   4,   1,  16,   2,   1,   1,   2,   1,   2,   1,   1,   9,   3,   1,   1,   2,   1,   1,   2,   3,   1,   1,   1,   1,   7,   1,  10,   2,   3,   3,   5,   4,   1,   1,   1,   2,   1,   1,   1,   1,   1,   1,   5,   5,   2,   2,   3,   2, 127,   5,   1,   1,   2,   1,   3,  25,   1,   4,   1,   1,   8,   1,  23,   1,   3,   6,   1,   1,   1,   1,   1,   5,   1,   1,   1,   1,  36,   1,   1,   2,   1,   1,   2,   1,   1,   4,   1,   2,   1,   1,   3,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,   2,   1,   1,   1,   1,   5,   3,   2,   3,   1,   1,   1,   1,   1,   2,   2,   1,   1,   1,   7,   3,   1,   1,   1,   1,   1,   2,   2,   2,   1,   1,   1,   1,   4,   1,   1,   1,   5,   1,   1,   1,   1,   3,   1,   2,   2,   2,   9,   1,   2,   3,   1,   2,   1,   9,   6,   2,   1,   5,   1,   1,   2,   1,   1,   3,   4,   1,  11,   1,   1,   3,   1,   1,  10,   1,   1,   1,   1,  15,   1,   2,   3,   2,   2,   1,   3,   1,  13,   1,   1,   4,   1,   1,   1,   2,   2,   1,   4,   2,   1,   4,   1,   1,   1,   1,   1,   1,   4,   1,   1,   1,   2,   1,   1,   1,   7,   1,   1,   2,   1,   4,   4,  33,  18,   7,   3,   1,   1,   3,   1,   1,   1,   1,  11,   1,   7,   2,   3,  17,   7,   6,   4,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   4,   1,   1,   2,   1,   4,   1,   2,   3,  10,  23,   2,   3,   2,   1,   5,   1,   1,  54,   1,   1,   1,   1,   2,   5,   1,  18,   1,   2,   1,   3,   2,   1,   2,   1,   1,   2,   1,   1,   1,   1,   1,   1,   1,   4,   2,   1,   1,   2,  18,   3,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,   1,   2,   2,   1,   1,   1,   4,   1,   3,   2,   1,   2,   5,   1,   1,   1,   1,   1,   5,   1,   1,   1,   1,   1,   1,   4,   2,   1,   2,   1,   1,   1,   1,   1,   2,   1,   3,   9,   1,   5,   1,   1,   1,   1,   1,   1,   7,   1,   2,   1,   1,   2,   4,   1,   2,   1,   1,   2,   2,   4,   5,   4,   1,   2,  14,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   2,   1,   1,   1,   2,   1,   1,   3,   2,   2,   1,   2,   1,   1,   3,   6,   1,   2,   1,   1,   1,   1,   1,   4,   1,   1,   5,   1,   1,   1,   9,   1,   1,   1,   2,   1,   3,   3,   7,   1,   1,   1,   1,   2,   2,   1,   1,   4,   1,   1,   1,   2,   9,   5,   1,   1,   2,   1,   7,   1,   1,   1,   1,   5,   1,   3,   2,   3,   1,   1,   2,   1,   1,   1,   1,   1,   2,   5,   4,   6,   2,   1,   1,   5,   1,   1,   1,   4,   1,  15,   2,  14,   2,   1,   1,   1,   1,   1,   1,   1,   5,   2,   1,   1,   1,   2,   1,   2,   3,   1,   2,   1,   1,   1,   2,   1,   6,   1,   1,   7,   1,   1,   1,   1,   2,   5,   1,   3,   2,   4,  13,   1,   1,   1,  20,   1,   1,   3,   1,   1,   5,   1,   2,   2,   1,   2,   1,   1,   1,   1,   1,   1,   5,   1,   1,   1,   1,   1,   1,  12,   2,   1,   3,   1,   1,   1,   1,   1,   1,   1,   2,   1,   2,   3,   1,   1,   4,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,   1,   1,   2,   1,   2,   2,   1,   1,   1,   1,   1,   1,   1,   2,   2,   1,   1,   1,   1,   2,   1,   1,   2,   2,   2,   2,   1,   1,   1,   1,   1,   1,   1,   4,   2,   1,   1,   6,   1,   1,   1,   1,   2,   1,   1,   1,   1,   1,   1,   3,   1,   1,   1,   1,   2,   1,   1,   1,   4,   2,   1,   2,   1,   1,   4,   1,   1,   2,   1,   2,   2,   1,   1,   1,   7,   1,   1,   1,   1,   1,   1,   2,   1,   1,   1,   1,   1,   1,   9,   1,   1,  15,   1,   1,   1,   1,   1,   1,   1,   1,   3,   3,   1,   1,   1,   1,   1,   2,   1,   1,   1,   1,   2,   8,   1,   1,   1,   3,   1,   2,   2,   1,   1,   2,   7,   1,   1,   2,   2,   1,   1,   4,   4,   1,  20,   2,   1,   1,   1,   1,   4,   4,   1,   1,   8,   1,   1,   1,   1,   1,   1,   4,   2,   1,   1,   1,   1,   2,   3,  17,   4,   1,   1,   1,   4,   1,   1,   1,   1,   1,   1,   6,   1,   1,   1,   2,   2,   1,   2,   1,   1,   1,   3,   2,   2,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,   1,  10,   2,   1,   5,   1,   1,   1,   1,   1,   1,   1,   9,   1,   2,   2,   1,   1,   3,   1,   1,   1,   1,   1,   1,   8,   1,   2,   1,   1,   2,   8,   2,   5,   6,   8,   2,   6,   5,   2,  10,   2,   4,   1,   2,   2,   1,   1,   1,   4,   1,   1,  19,   2,   1,   3,   6,   1,   1,   1,   2,   1,   2,   1,   1,   1,   1,   1,   6,   1,   1,   1,   4,   3,   1,   1,   1,   2,   3,   2,   1,   1,   1,  14,   1,   1,   3,   7,   1,   1,   1,   3,   2,   2,   2,   3,   3,   1,   1,   1,   7,   1,   1,   1,   1,   1,   4,   2,   2,   5,   2,   3,   1,   2,  22,   3,   3,   1,   1,   1,   1,   8,   1,   2,   1,   1,   1,   1,   1,   1,   6,   1,   1,   1,   9,   5,   1,   1,   1,   3,   1,   1,   1,   1,   1,   1,   1,   1,  33,   1,   1,   1,   1,   1,   1,   1,  80,   3,   1,   2,   2,   3,   1,   1,   3,   7,   1,   1,   1,   2,   1,   1,   4,   1,   1,   4,   1,   1,   1,   1,  23,   2,   4,   6,   2,   1,   2,   1,   1,   1,   1,   3,   1,   1,   3,   1,  10,   3,   1,   1,  15,   1,   1,   5,  10,   9,   1,   1,   1,   1,   2,   2,   1,   2,   8,   1,  21,   1,   1,   3,   1,   1,   1,  21,   2,   3,   1,   3,   1,   1,   3,   2,   1,   1,   1,   1,   2,   1,   1,   1,   3,   1,   1,   1,   1,   5,   1,   3,  27,   2,   1,   1,   1,   1,   1,   1,   1,   2,   6,   1,   1,   1,   1,   5,   1,  25,  15,  12,   1,   1,   2,   1,  28,   1,   2,   3,   2,   1,   1,   1,   1,   1,   1,   1,   1,   1,  27,   1,   1,   1,   1,  18,   2,   1,   2,   4,   1,   2,   2,   1,   1,   4,   3,   1,   1,   1,   2,   1,   1,   2,   1,   1,   2,   1,   2,   2,   2,   1,   2,   2,   2,   8,   1,   1,   1,   3,  15,  10,   1,   1,   1,   3,   1,   1,   1,   3,   1,   4,   1,   1,   1,   1,   1,   1,   6,   4,   1,   1,   1,   1,   1,   1,   1,   1,   6,   1,   3,   2,  13,   1,   1,   1,   4,   4,   1,   1,   1,   2,   3,   1,   1,   1,   1,   1,   1,   1,   1,   5,   1,   3,   1,   1,   2,   3,   1,   1,   7,   3,   2,   1,   4,   1,   1,   4,   3,   1,   1,   1,   1,   8,   2,   1,   1,   1,   1,   2,   4,   4,   6,   1,   1,   2,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   4,   3,   1,   3,   2,   1,   3,   1,   2,   1,   1,   1,   1,   1,   2,   1,   2,   1,   1,   1,   1,   3,   3,   4,   1,   1,   6,   1,   1,   1,   1,   1,   1,   3,   2,   1,   1,   1,   2,   4,   1,   1,   1,   1,   1,   4,  11,   1,   1,   2,   1,   1,   8,   2,   1,   2, 169,   4,  40,   1,   1,   4,   1,   1,  40,   1,   1,   1,   1,   4,   1,   1,   1,   7,   3,   1,   4,   1,   1,   5,   9,   2,  15,   1,   2,   1,   2,   2,   1,   1,   6,   4,   2,   1,   1,   1,   1,   1,   3,   1,   2,   1,   6,   1,   3,   1,   1,   1,   3,   1,   2,   1,   1,   3,   1,   1,   1,   1,   2,  11,   4,   4,   1,   1,   1,   1,   1,   1,   4,   1,   1,   1,   1,   1,   1,   1,  31,  19,   2,   1,   3,   1,   7,   9,   1,   1,   2,   1,   1,   2,   3,   1,   1,   2,   1,   1,   1,   1,   2,   1,   1,   1,   6,   1,   1,   1,   1,   3,   1,   2,   1,   1,   1,   1,   1,   1,   1,   5,   1,   2,   2,   1,   1,   2,   1,   1,   1,   1,  21,   1,   1,   1,   3,   1,   1,   1,   1,   5,   1,   2,   1,   1,   7,   4,   1,   1,   2,   1,   1,   1,   1,   1,   1,   1,   1,   4,   4,   3,   2,   1,   2,   1,   2,   2,   1,   2,   1,   2,   1,   1,   1,   5,   3,   2,   2,   1,   4,   1,   3,   1,  21,   3,   1,   1,   1,   1,   1, 100,   2,   1,   5,   1,   1,   3,   3,   1,   1,   1,   1,   1,   2,   3,   1,   1,   1,   1,   1,   1,  12,   4,   1,   2,   1,   2,   1,   1,   1,   9,   4,   1,   1,   1,   1,   1,   1,   1,   2,   3,   1,   3,   1,   1,   1,   1,   1,   2,   1,   1,   1,   1,   1,   1,   1,   1,   3,   2,   1,   1,   1,   1,   1,   1,   5,   1,   1,   1,   1,   2,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,   1,   1,   1,   6,   1,   9,   1,   1,   2,   4,   1,   1,   2,   4,   1,   1,   1,   1,   4,   1,   1,   1,   1,   2,   1,   3,   1,   1,   1,   1,   1,   2,   3,   1,   1,   1,   1,   2,   1,   1,   1,   1,  26,   1,   1,   3,   1,   1,   1,   9,   9,   1,   1,   6,   3,   1,   1,   1,   6,   2,   1,   1,   1,   1,   1,   2,   4,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,   1,   2,   2,   1,   4,   1,   1,   1,   6,   1,   1,   6,   1,   2,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   9,   3,   1,   1,   1,   3,   4,   1,   1,   2,   2,   9,   1,  12,   2,   1,   5,   4,   3,   4,   1,  24,   1,   1,   1,   1,   1,   2,  12,   1,   1,   1,   5,   1,   1,  16,   2,   1,   1,   1,   1,   1,   1,   3,   2,   2,   2,   3,   1,   1,   1,   3,   1,   2,   2,   2,   1,   2,   1,   1,   3,   1,   1,   1,   1,   1,   1,   2,   1,   1,   8,   1,   2,   2,   1,   2,   1,   1,   1,   1,   7,   2,   1,   2,   5,   1,   2,   1,   1,   1,   3,   1,   1,   1,  22,   1,   1,   2,   1,   1,   2,   1,   1,   1,   2,   2,   1,   5,   1,   1,   1,   1,   9,   3,   2,   2,   2,   1,   2,   3,   1,   2,   8,   2,   1,   1,   3,   1,   3,   1,   1,   1,   1,   2,   1,   1,   1,   1,   1,   3,   1,   2,   1,   1,   2,   1,   2,   1,   1,   1,   3,   1,   1,   2,   1,   1,   1,   1,   3,   2,   1,   1,   1,   1,   2,   1,   1,   1,   5,   1,   1,   1,   1,   1,   1,   1,   7,   1,   2,   1,   1,   1,   1,   1,   1,   1,   1,   4,   1,   1,   3,   1,   1,   1,   1,   1,   2,   2,  10,   1,   1,   2,   1,   1,   2,   2,   2,   1,   1,   1,   1,   1,   2,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   3,   1,   2,   2,   1,   1,   2,  11,   3,   1,   1,   1,   4,   1,   1,   1,   1,   4,   1,   1,   2,   1,  15,   3,   1,   3,   3,   1,   1,  39,   1,   4,   1,   1,   1,   1,   2,   1,   1,   1,   2,   1,   1,   2,   1,   2,   1,   2,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   3,   4,   1,   1,   2,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,   1,   1,   9,   2,   1,   1,   1,   5,   1,   1,   2,   1,   1,   2,   1,   1,   1,   3,   1,   2,   1,   1,   1,   1,   1,   3,   1,   1,   1,   1,   2,   1,   1,   1,   1,   1,   2,   1,   2,   2,   1,   1,   1,   1,   1,   2,   1,   1,   1,   3,   9,   1,   1,   1,   2,   1,   2,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   3,   1,   1,   1,   1,   2,   1,   1,   1,   1,   3,   2,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,   2,   1,   1,   1,   7,   1,  15,   1,   1,   2,   2,   1,   1,   1,   2,   2,   1,   1,   1,   1,   1,   1,   5,   1,   1,   1,   1,   1,   3,   1,   9,   1,   6,   1,   1,   3,   1,   1,   7,   1,   2,   1,   1,   1,   4,   1,   2,   1,   2,   1,   1,  10,   2,   1,   1,   2,   1,   1,   1,   3,   2,   1,   1,   1,   4,   5,   1,   1,   4,   2,   2,   2,   1,   2,   2,   1,   1,   3,   2,   1,   1,   1,   1,   5,   3,   1,   1,   1,   2,   1,   2,   2,   2,   1,   1,   1,   1,   2,   1,   4,   1,   6,  10,  22,   4,   4,   1,   1,   1,   3,   1,   1,   1,   1,   4,   1,   3,   1,  29,  26,   1,   1,   1,   1,   1,   1,   5,   1,   2,   2,   3,   1,   1,   3,   2,   1,   1,   1,   9,   1,   5,   1,   1,   1,   7,   1,   3,   1,   1,   1,   2,   1,   2,   1,   2,   5,   1,   1,   6,   1,   2,  52,   5,   2,   6,   4,   1,  10,  30,   2,   1,   1,   1,   1,   1,   1,   1,   1,  10,   2,   1,   3,   3,   2,   1,   1,   6,   1,   2,   2,   5,   6,   9,   1,   3,   1,   1,   1,   5,   1,   3,   2,   3,   1,   7,   8,   1,   1,   2,   1,   1,   1,   1,   1,   3,   1,   1,   1,   1,   1,   3,   2,   1,   1,   1,   2,   2,   1,   1,   1,   1,   2,   4,   1,   1,   1,   1,   1,   4,   2,   1,   5,   4,   1,   4,   2,   7,   4,   1,   2,  16,   1,   2,   3,   1,   1,   1,   7,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   2,   1,   1,   1,   1,   1,   1,   4,   2,   7,   1,   2,   2,   1,   2,  11,   1,  10,   2,   3,   1,   1,   3,   5,   1,   7,   2,   1,   1,   4,   2,   1,   2,   1,   1,   1,   1,   3,   2,   2,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,   1,   1,   1,   1,   1,   1,   6,   1,   1,   1,   1,   2,   8,   1,   2,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   3,   1,   4,   1,   2,  10,  21,   1,   2,   2,   1,   6,   3,   2,   1,   2,   5,   1,   1,   1,   1,   6,   1,   1,   1,   1,   1,   4,   1,   4,   1,   4,   9,   1,   1,   1,   1,   2,   1,   1,   2,   7,   1,   1,   2,   2,   1,   1,   3,   1,   2,   3,   1,   1,   3,   1,   1,   1,   1,   1,   2,   1,   1,   1,   1,   5,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   2,   1,   1,   1,   1,   2,   3,   1,   1,   1,   1,   1,   8,   1,   1,   3,  10,   3,   4,   1,   3,   1,   1,   1,   3,   1,   1,   1,   5,   1,   1,   2,   3,   1,   1,   1,   2,   2,   4,   1

In [ ]:
# Yukarıda hangi kelimenin kaç kere geçtiğini karmaşık bir şekilde görüyoruz. Bunu daha güzel bir şekilde görelim

word_freq = dict(zip(feature_names , word_counts))
word_freq

# Bunları frekansına göre sıralayalım
sorted_word_freq = dict(sorted(word_freq.items(), key=lambda item: item[1], reverse=True))  # item[1] değere (frekans) göre sıralama yapar, item[0] ise anahtara (kelimeler) göre sıralama yapar
sorted_word_freq



# !!!!!!!!!!!!!!

# STOP WORDS'LERİN KALDIRIMI:

# Gördüğümüz gibi the: 1378, and: 645, this: 258 gibi kelimeler en çok geçen kelimeler olmuş ki biz şu an sadaece ilk 100 yorum ile çalışıyoruz.
# Bu kelimeleri stop-word olarak adlandırıyorduk ve genellikle metin madenciliği ve doğal dil işleme görevlerinde çıkarılırlar.
# Çünkü bu tür kelimeler genellikle anlam taşımazlar ve modelin performansını olumsuz etkileyebilirler.

# !!!!!
# Bunun için "clean_text" fonksiyonumuzu GÜNCELLEDİK buraya kadar tekar çalıştırdık

{'movie': 169,
 'film': 127,
 'one': 100,
 'like': 80,
 'even': 58,
 'good': 54,
 'see': 52,
 'story': 45,
 'would': 43,
 'movies': 40,
 'much': 40,
 'really': 39,
 'bad': 36,
 'first': 36,
 'time': 35,
 'could': 34,
 'get': 33,
 'life': 33,
 'way': 33,
 'dont': 32,
 'never': 31,
 'also': 30,
 'seen': 30,
 'scene': 29,
 'well': 29,
 'man': 28,
 'young': 28,
 'acting': 27,
 'made': 27,
 'many': 27,
 'character': 26,
 'people': 26,
 'scenes': 26,
 'still': 26,
 'end': 25,
 'films': 25,
 'make': 25,
 'best': 24,
 'characters': 24,
 'plot': 24,
 'find': 23,
 'going': 23,
 'little': 23,
 'least': 22,
 'pretty': 22,
 'say': 22,
 'think': 22,
 'two': 22,
 'war': 22,
 'cant': 21,
 'lot': 21,
 'love': 21,
 'nothing': 21,
 'old': 21,
 'something': 21,
 'better': 20,
 'however': 20,
 'ive': 20,
 'three': 20,
 'watch': 20,
 'worst': 20,
 'actors': 19,
 'another': 19,
 'back': 19,
 'know': 19,
 'new': 19,
 'thing': 19,
 'gets': 18,
 'got': 18,
 'great': 18,
 'mario': 18,
 'though': 18,
 'years': 18,
 'around': 17,
 'ever': 17,
 'give': 17,
 'jimmy': 17,
 'actually': 16,
 'far': 16,
 'police': 16,
 'show': 16,
 'times': 16,
 'want': 16,
 'watching': 16,
 'work': 16,
 'cast': 15,
 'didnt': 15,
 'funny': 15,
 'hollywood': 15,
 'interesting': 15,
 'look': 15,
 'makes': 15,
 'may': 15,
 'must': 15,
 'real': 15,
 'right': 15,
 'take': 15,
 'theres': 15,
 'thought': 15,
 'use': 15,
 'audience': 14,
 'big': 14,
 'director': 14,
 'hard': 14,
 'home': 14,
 'last': 14,
 'things': 14,
 'world': 14,
 'anyone': 13,
 'fact': 13,
 'game': 13,
 'house': 13,
 'men': 13,
 'sure': 13,
 'violence': 13,
 'becomes': 12,
 'comes': 12,
 'different': 12,
 'idea': 12,
 'making': 12,
 'original': 12,
 'played': 12,
 'point': 12,
 'success': 12,
 'true': 12,
 'truly': 12,
 'try': 12,
 'whole': 12,
 'although': 11,
 'doesnt': 11,
 'full': 11,
 'girl': 11,
 'mother': 11,
 'need': 11,
 'rather': 11,
 'simply': 11,
 'taken': 11,
 'thats': 11,
 'tom': 11,
 'top': 11,
 'used': 11,
 'woman': 11,
 'away': 10,
 'beautiful': 10,
 'beginning': 10,
 'believe': 10,
 'bit': 10,
 'bring': 10,
 'course': 10,
 'feeling': 10,
 'fun': 10,
 'goes': 10,
 'kane': 10,
 'kind': 10,
 'long': 10,
 'looking': 10,
 'maybe': 10,
 'quite': 10,
 'rose': 10,
 'saw': 10,
 'seems': 10,
 'sense': 10,
 'since': 10,
 'someone': 10,
 'stars': 10,
 'takes': 10,
 'trying': 10,
 'turns': 10,
 'watched': 10,
 'wife': 10,
 'without': 10,
 'actor': 9,
 'almost': 9,
 'awful': 9,
 'become': 9,
 'black': 9,
 'cinema': 9,
 'comedy': 9,
 'enough': 9,
 'entertainment': 9,
 'especially': 9,
 'every': 9,
 'everything': 9,
 'example': 9,
 'eyes': 9,
 'father': 9,
 'fred': 9,
 'friend': 9,
 'half': 9,
 'help': 9,
 'hes': 9,
 'interest': 9,
 'keep': 9,
 'let': 9,
 'looks': 9,
 'musical': 9,
 'nice': 9,
 'others': 9,
 'part': 9,
 'performance': 9,
 'performances': 9,
 'place': 9,
 'play': 9,
 'probably': 9,
 'remember': 9,
 'rest': 9,
 'role': 9,
 'screen': 9,
 'series': 9,
 'space': 9,
 'terrible': 9,
 'took': 9,
 'wait': 9,
 'yes': 9,
 'based': 8,
 'bmovie': 8,
 'came': 8,
 'completely': 8,
 'dialogue': 8,
 'done': 8,
 'dvd': 8,
 'earlier': 8,
 'effects': 8,
 'finally': 8,
 'involved': 8,
 'japanese': 8,
 'kid': 8,
 'kids': 8,
 'killer': 8,
 'left': 8,
 'lost': 8,
 'matter': 8,
 'mind': 8,
 'mountain': 8,
 'power': 8,
 'production': 8,
 'sex': 8,
 'small': 8,
 'star': 8,
 'stupid': 8,
 'ten': 8,
 'upon': 8,
 'version': 8,
 'wasnt': 8,
 'worth': 8,
 'year': 8,
 'absolutely': 7,
 'act': 7,
 'along': 7,
 'book': 7,
 'called': 7,
 'coburn': 7,
 'dark': 7,
 'death': 7,
 'direction': 7,
 'enjoy': 7,
 'entire': 7,
 'face': 7,
 'family': 7,
 'fan': 7,
 'feel': 7,
 'forget': 7,
 'genre': 7,
 'getting': 7,
 'girls': 7,
 'given': 7,
 'hand': 7,
 'henry': 7,
 'high': 7,
 'horror': 7,
 'instead': 7,
 'isnt': 7,
 'later': 7,
 'law': 7,
 'lines': 7,
 'might': 7,
 'murder': 7,
 'next': 7,
 'number': 7,
 'predictable': 7,
 'put': 7,
 'ridiculous': 7,
 'romantic': 7,
 'script': 7,
 'several': 7,
 'shot': 7,
 'shows': 7,
 'similar': 7,
 'sir': 7,
 'special': 7,
 'totally': 7,
 'unique': 7,
 'women': 7,
 'writing': 7,
 'yet': 7,
 'action': 6,
 'actress': 6,
 'anything': 6,
 'average': 6,
 'blood': 6,
 'boring': 6,
 'brought': 6,
 'business': 6,
 'certainly': 6,
 'child': 6,
 'city': 6,
 'classic': 6,
 'cold': 6,
 'cry': 6,
 'disappointed': 6,
 'drama': 6,
 'dresser': 6,
 'ending': 6,
 'entertaining': 6,
 'falls': 6,
 'fine': 6,
 'friends': 6,
 'gives': 6,
 'heard': 6,
 'hitchcocks': 6,
 'horrible': 6,
 'indian': 6,
 'john': 6,
 'killed': 6,
 'killing': 6,
 'knows': 6,
 'lack': 6,
 'less': 6,
 'lives': 6,
 'main': 6,
 'meet': 6,
 'memorable': 6,
 'minutes': 6,
 'money': 6,
 'name': 6,
 'nasty': 6,
 'nominated': 6,
 'parents': 6,
 'perhaps': 6,
 'person': 6,
 'picture': 6,
 'piece': 6,
 'roles': 6,
 'saving': 6,
 'secret': 6,
 'seem': 6,
 'sequel': 6,
 'serial': 6,
 'slow': 6,
 'son': 6,
 'sort': 6,
 'stop': 6,
 'thinking': 6,
 'title': 6,
 'titta': 6,
 'turn': 6,
 'type': 6,
 'usually': 6,
 'view': 6,
 'voice': 6,
 'wonderful': 6,
 'worse': 6,
 'wouldnt': 6,
 'wrong': 6,
 'adventure': 5,
 'always': 5,
 'among': 5,
 'apparently': 5,
 'attempt': 5,
 'behind': 5,
 'believable': 5,
 'beyond': 5,
 'boll': 5,
 'bored': 5,
 'boy': 5,
 'brings': 5,
 'cannot': 5,
 'carver': 5,
 'case': 5,
 'castle': 5,
 'cause': 5,
 'cell': 5,
 'change': 5,
 'children': 5,
 'come': 5,
 'couple': 5,
 'courtenay': 5,
 'day': 5,
 'decides': 5,
 'despite': 5,
 'dozen': 5,
 'due': 5,
 'dutcher': 5,
 'elements': 5,
 'else': 5,
 'eventually': 5,
 'evil': 5,
 'exactly': 5,
 'extremely': 5,
 'felt': 5,
 'fight': 5,
 'fighting': 5,
 'filmbr': 5,
 'finney': 5,
 'follow': 5,
 'found': 5,
 'front': 5,
 'golf': 5,
 'gore': 5,
 'guess': 5,
 'gun': 5,
 'halfway': 5,
 'happens': 5,
 'hell': 5,
 'heston': 5,
 'highly': 5,
 'hit': 5,
 'hold': 5,
 'honestly': 5,
 'hot': 5,
 'human': 5,
 'husband': 5,
 'karen': 5,
 'kill': 5,
 'killings': 5,
 'leads': 5,
 'lets': 5,
 'looked': 5,
 'machine': 5,
 'major': 5,
 'michael': 5,
 'music': 5,
 'norman': 5,
 'novel': 5,
 'offers': 5,
 'ones': 5,
 'painful': 5,
 'playing': 5,
 'points': 5,
 'premise': 5,
 'prison': 5,
 'pure': 5,
 'reminds': 5,
 'robert': 5,
 'running': 5,
 'sally': 5,
 'school': 5,
 'screenplay': 5,
 'second': 5,
 'seeing': 5,
 'sequences': 5,
 'set': 5,
 'shoot': 5,
 'single': 5,
 'soon': 5,
 'spoiler': 5,
 'stay': 5,
 'style': 5,
 'successful': 5,
 'surf': 5,
 'surprise': 5,
 'talented': 5,
 'talk': 5,
 'tell': 5,
 'tells': 5,
 'theme': 5,
 'throughout': 5,
 'thus': 5,
 'together': 5,
 'touch': 5,
 'towards': 5,
 'town': 5,
 'tragedy': 5,
 'turned': 5,
 'turning': 5,
 'twists': 5,
 'unbelievable': 5,
 'unfortunately': 5,
 'unless': 5,
 'usual': 5,
 'virgin': 5,
 'warned': 5,
 'water': 5,
 'wealthy': 5,
 'weird': 5,
 'within': 5,
 'works': 5,
 'york': 5,
 'actual': 4,
 'ada': 4,
 'aftermath': 4,
 'air': 4,
 'amazing': 4,
 'american': 4,
 'anand': 4,
 'annoying': 4,
 'army': 4,
 'arts': 4,
 'band': 4,
 'barnes': 4,
 'basically': 4,
 'began': 4,
 'begins': 4,
 'bela': 4,
 'blockbuster': 4,
 'bowser': 4,
 'call': 4,
 'care': 4,
 'century': 4,
 'chance': 4,
 'cheap': 4,
 'coming': 4,
 'conseguenze': 4,
 'constantly': 4,
 'control': 4,
 'cops': 4,
 'couldnt': 4,
 'crappy': 4,
 'cristy': 4,
 'crocky': 4,
 'crocodile': 4,
 'cut': 4,
 'dated': 4,
 'daughter': 4,
 'deep': 4,
 'definitely': 4,
 'dellamore': 4,
 'difficult': 4,
 'door': 4,
 'dream': 4,
 'durbin': 4,
 'early': 4,
 'either': 4,
 'entirely': 4,
 'everyone': 4,
 'excellent': 4,
 'except': 4,
 'experience': 4,
 'eye': 4,
 'fails': 4,
 'familiar': 4,
 'fans': 4,
 'fantastic': 4,
 'female': 4,
 'final': 4,
 'flat': 4,
 'forward': 4,
 'fulcis': 4,
 'gang': 4,
 'gary': 4,
 'gave': 4,
 'gem': 4,
 'george': 4,
 'german': 4,
 'giving': 4,
 'glory': 4,
 'god': 4,
 'graphic': 4,
 'grudge': 4,
 'guy': 4,
 'hands': 4,
 'happening': 4,
 'happy': 4,
 'held': 4,
 'hero': 4,
 'hitchcock': 4,
 'holes': 4,
 'hours': 4,
 'imdb': 4,
 'indeed': 4,
 'inman': 4,
 'inside': 4,
 'italy': 4,
 'itbr': 4,
 'jake': 4,
 'james': 4,
 'jeep': 4,
 'jimmys': 4,
 'job': 4,
 'king': 4,
 'knew': 4,
 'lame': 4,
 'lead': 4,
 'listen': 4,
 'lite': 4,
 'live': 4,
 'married': 4,
 'martial': 4,
 'meanwhile': 4,
 'meets': 4,
 'mention': 4,
 'mentioned': 4,
 'miles': 4,
 'milland': 4,
 'minor': 4,
 'minute': 4,
 'mission': 4,
 'moments': 4,
 'mormon': 4,
 'mostly': 4,
 'moviebr': 4,
 'moving': 4,
 'mumbai': 4,
 'murders': 4,
 'named': 4,
 'needed': 4,
 'needs': 4,
 'neither': 4,
 'numerous': 4,
 'obvious': 4,
 'obviously': 4,
 'often': 4,
 'originally': 4,
 'otherwise': 4,
 'particularly': 4,
 'pass': 4,
 'past': 4,
 'peter': 4,
 'pick': 4,
 'planets': 4,
 'plays': 4,
 'plenty': 4,
 'quality': 4,
 'ray': 4,
 'read': 4,
 'reason': 4,
 'relationship': 4,
 'room': 4,
 'run': 4,
 'ryan': 4,
 'save': 4,
 'saying': 4,
 'says': 4,
 'scary': 4,
 'seemed': 4,
 'shes': 4,
 'shock': 4,
 'shooting': 4,
 'short': 4,
 'shots': 4,
 'silly': 4,
 'sitting': 4,
 'solid': 4,
 'sound': 4,
 'soundtrack': 4,
 'southern': 4,
 'started': 4,
 'stephen': 4,
 'stereotypical': 4,
 'storyline': 4,
 'stuff': 4,
 'subject': 4,
 'superior': 4,
 'supposed': 4,
 'surprisingly': 4,
 'system': 4,
 'taking': 4,
 'talking': 4,
 'television': 4,
 'terrific': 4,
 'thriller': 4,
 'told': 4,
 'train': 4,
 'trouble': 4,
 'typical': 4,
 'unfolds': 4,
 'viewing': 4,
 'walk': 4,
 'wanna': 4,
 'wanted': 4,
 'wanting': 4,
 'wants': 4,
 'waste': 4,
 'ways': 4,
 'whether': 4,
 'white': 4,
 'whos': 4,
 'wont': 4,
 'worked': 4,
 'write': 4,
 'written': 4,
 'youre': 4,
 'accepted': 3,
 'accurate': 3,
 'adding': 3,
 'affair': 3,
 'affected': 3,
 'alexandra': 3,
 'alive': 3,
 'already': 3,
 'altogether': 3,
 'america': 3,
 'amount': 3,
 'appears': 3,
 'approach': 3,
 'arff': 3,
 'art': 3,
 'auer': 3,
 'aware': 3,
 'barely': 3,
 'battle': 3,
 'bigger': 3,
 'bill': 3,
 'bizarre': 3,
 'bluff': 3,
 'bmovies': 3,
 'board': 3,
 'bought': 3,
 'brady': 3,
 'brilliance': 3,
 'brilliant': 3,
 'brown': 3,
 'bush': 3,
 'camera': 3,
 'carpenter': 3,
 'carrey': 3,
 'changed': 3,
 'charles': 3,
 'cheesy': 3,
 'childhood': 3,
 'clearly': 3,
 'compared': 3,
 'compelling': 3,
 'complete': 3,
 'confusing': 3,
 'consequences': 3,
 'constant': 3,
 'convincing': 3,
 'count': 3,
 'country': 3,
 'create': 3,
 'created': 3,
 'creating': 3,
 'creatures': 3,
 'crime': 3,
 'dad': 3,
 'dancing': 3,
 'darker': 3,
 'david': 3,
 'davis': 3,
 'days': 3,
 'dealt': 3,
 'deanna': 3,
 'decent': 3,
 'deeply': 3,
 'delightful': 3,
 'delivers': 3,
 'describes': 3,
 'desired': 3,
 'detective': 3,
 'development': 3,
 'dialog': 3,
 'die': 3,
 'directors': 3,
 'disappointing': 3,
 'disaster': 3,
 'documentary': 3,
 'double': 3,
 'doug': 3,
 'drunk': 3,
 'dubbed': 3,
 'easier': 3,
 'eating': 3,
 'effort': 3,
 'emotional': 3,
 'employer': 3,
 'english': 3,
 'enjoyed': 3,
 'entrails': 3,
 'episode': 3,
 'eriksen': 3,
 'exception': 3,
 'expect': 3,
 'expectations': 3,
 'explicit': 3,
 'failed': 3,
 'fake': 3,
 'famous': 3,
 'fathers': 3,
 'favourite': 3,
 'fell': 3,
 'fellow': 3,
 'figured': 3,
 'filmmaker': 3,
 'finds': 3,
 'flick': 3,
 'followed': 3,
 'following': 3,
 'forgettable': 3,
 'franchise': 3,
 'french': 3,
 'fulci': 3,
 'fully': 3,
 'future': 3,
 'galaxy': 3,
 'ghost': 3,
 'giallo': 3,
 'girolamos': 3,
 'godzilla': 3,
 'golden': 3,
 'grace': 3,
 'greatest': 3,
 'gruesome': 3,
 'hal': 3,
 'havent': 3,
 'hear': 3,
 'helps': 3,
 'hence': 3,
 'hilarious': 3,
 'hills': 3,
 'hope': 3,
 'hotel': 3,
 'huge': 3,
 'identity': 3,
 'imagination': 3,
 'influence': 3,
 'intriguing': 3,
 'introduced': 3,
 'irish': 3,
 'jim': 3,
 'journey': 3,
 'kept': 3,
 'known': 3,
 'land': 3,
 'language': 3,
 'late': 3,
 'latter': 3,
 'laughed': 3,
 'laughs': 3,
 'learn': 3,
 'leave': 3,
 'leaves': 3,
 'levels': 3,
 'liked': 3,
 'limited': 3,
 'line': 3,
 'london': 3,
 'loneliness': 3,
 'longer': 3,
 'lots': 3,
 'loved': 3,
 'lovers': 3,
 'low': 3,
 'lumas': 3,
 'mad': 3,
 'manager': 3,
 'martin': 3,
 'maximum': 3,
 'mean': 3,
 'means': 3,
 'memories': 3,
 'message': 3,
 'middle': 3,
 'midler': 3,
 'mike': 3,
 'million': 3,
 'missionaries': 3,
 'mistake': 3,
 'mitchum': 3,
 'mom': 3,
 'moment': 3,
 'monster': 3,
 'murderer': 3,
 'narrative': 3,
 'national': 3,
 'nature': 3,
 'nearly': 3,
 'news': 3,
 'night': 3,
 'none': 3,
 'noticed': 3,
 'occasional': 3,
 'office': 3,
 'okay': 3,
 'older': 3,
 'onto': 3,
 'open': 3,
 'opinion': 3,
 'outside': 3,
 'overall': 3,
 'pace': 3,
 'paul': 3,
 'peach': 3,
 'perfect': 3,
 'period': 3,
 'places': 3,
 'planet': 3,
 'please': 3,
 'poor': 3,
 'porno': 3,
 'portrait': 3,
 'possible': 3,
 'presented': 3,
 'problem': 3,
 'producers': 3,
 'program': 3,
 'project': 3,
 'protagonist': 3,
 'provide': 3,
 'public': 3,
 'question': 3,
 'rape': 3,
 'rating': 3,
 'realism': 3,
 'reality': 3,
 'realize': 3,
 'relations': 3,
 'rent': 3,
 'replacement': 3,
 'responsible': 3,
 'return': 3,
 'revenge': 3,
 'rock': 3,
 'romance': 3,
 'ruin': 3,
 'safety': 3,
 'salman': 3,
 'scale': 3,
 'scenario': 3,
 'scientist': 3,
 'score': 3,
 'scripts': 3,
 'sent': 3,
 'sentence': 3,
 'seriously': 3,
 'sets': 3,
 'settled': 3,
 'shakespeare': 3,
 'shame': 3,
 'showed': 3,
 'singer': 3,
 'singing': 3,
 'skilled': 3,
 'soldiers': 3,
 'song': 3,
 'speed': 3,
 'spend': 3,
 'spider': 3,
 'standards': 3,
 'starring': 3,
 'start': 3,
 'starts': 3,
 'station': 3,
 'steele': 3,
 'steve': 3,
 'stories': 3,
 'straight': 3,
 'stronger': 3,
 'struck': 3,
 'struggle': 3,
 'stunning': 3,
 'sturgis': 3,
 'subtle': 3,
 'suddenly': 3,
 'suicide': 3,
 'super': 3,
 'surely': 3,
 'suspense': 3,
 'swear': 3,
 'sympathetic': 3,
 'tedious': 3,
 'telling': 3,
 'temple': 3,
 'tension': 3,
 'terror': 3,
 'thanks': 3,
 'theater': 3,
 'themes': 3,
 'theyre': 3,
 'theyve': 3,
 'thrills': 3,
 'thrown': 3,
 'timebr': 3,
 'tired': 3,
 'today': 3,
 'torture': 3,
 'tracy': 3,
 'trade': 3,
 'trailer': 3,
 'tried': 3,
 'tries': 3,
 'twist': 3,
 'ultimately': 3,
 'unexpectedly': 3,
 'universe': 3,
 'unlike': 3,
 'unsympathetic': 3,
 'utterly': 3,
 'vhs': 3,
 'victim': 3,
 'video': 3,
 'visual': 3,
 'waiting': 3,
 'wars': 3,
 'watchable': 3,
 'waybr': 3,
 'week': 3,
 'went': 3,
 'werent': 3,
 'western': 3,
 ...}