In [ ]:
# Kütüphanelerimiz import edelim
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [4]:
# Veri seitimizi yükleyelim
# Veri setini biraz temizlememiz gerekiyor

df = pd.read_csv("spam.csv" , encoding="latin-1")
df = df.rename(columns={"v1": "type", "v2": "text"})
df.drop(columns={"Unnamed: 2", "Unnamed: 3", "Unnamed: 4"}, inplace=True)
df.head()

   type                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
# Kütüphanemizi kullanmak için TF-IDF vektörleştiricimizi oluşturalım

vectorizer = TfidfVectorizer()

In [6]:
# Metinlerimizi vektörleştirelim

x = vectorizer.fit_transform(df["text"])

In [7]:
# Kelime kümemizi bulalım

feature_names = vectorizer.get_feature_names_out()
tfidf_score = x.mean(axis=0).A1 # Her kelimenin tüm belgelerdeki TF-IDF ortalamasını bulalım

In [8]:
# Sonuçları bir dataframe olarak görelim

df = pd.DataFrame({"word": feature_names, "tfidf_score": tfidf_score})
df

# Metinlerimizi temizlemediğimiz için bu şekilde saçma kelimler çıkıyor. 
# Normalde vektörleştirmeden önce metin temizliği yapmamız gerekiyordu.
# Temizlemeden vektörleştirirsek ne olacağını görmek için bunu yaptık.

              word  tfidf_score
0               00     0.000402
1              000     0.001161
2           000pes     0.000042
3     008704050406     0.000094
4             0089     0.000045
...            ...          ...
8667          ûªve     0.000051
8668            ûï     0.000052
8669       ûïharry     0.000052
8670            ûò     0.000441
8671        ûówell     0.000065

[8672 rows x 2 columns]

In [9]:
# Bu df'i sıralayarak en önemli kelimeleri görebiliriz
df = df.sort_values(by="tfidf_score", ascending=False)
df

            word  tfidf_score
8609         you     0.044145
7756          to     0.036946
7627         the     0.026384
4087          in     0.021946
4939          me     0.021159
...          ...          ...
6597      sambar     0.000013
4850     makiing     0.000013
7075     sorrows     0.000013
1279  attraction     0.000013
6002     praises     0.000013

[8672 rows x 2 columns]